import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Initial schema — faithful PostgreSQL port of the SQLite schema
 * (base tables + M001..M005), including all CHECK constraints and indexes.
 *
 * Deliberate deviations (documented):
 *  - `sessions` table is replaced by JWT + `refresh_tokens`.
 *  - audit_log.details is jsonb instead of TEXT.
 *  - timestamps are timestamptz.
 */
export class Init1756000000000 implements MigrationInterface {
  name = 'Init1756000000000';

  async up(qr: QueryRunner): Promise<void> {
    await qr.query(`CREATE TABLE users (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      username text NOT NULL,
      display_name text NOT NULL DEFAULT '',
      password_hash text NOT NULL,
      role text NOT NULL DEFAULT 'cashier' CONSTRAINT users_role_chk CHECK (role IN ('owner','admin','manager','cashier')),
      status text NOT NULL DEFAULT 'active' CONSTRAINT users_status_chk CHECK (status IN ('active','disabled')),
      must_change_password integer NOT NULL DEFAULT 0,
      failed_attempts integer NOT NULL DEFAULT 0,
      locked_until timestamptz,
      last_login_at timestamptz,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz
    )`);
    await qr.query('CREATE UNIQUE INDEX idx_users_username_nocase ON users (lower(username))');

    await qr.query(`CREATE TABLE refresh_tokens (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      token_hash text NOT NULL UNIQUE,
      user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      created_at timestamptz NOT NULL DEFAULT now(),
      expires_at timestamptz NOT NULL,
      revoked_at timestamptz
    )`);
    await qr.query('CREATE INDEX idx_refresh_tokens_user ON refresh_tokens(user_id)');
    await qr.query('CREATE INDEX idx_refresh_tokens_expires ON refresh_tokens(expires_at)');

    await qr.query(`CREATE TABLE audit_log (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      actor_id integer REFERENCES users(id) ON DELETE SET NULL,
      action text NOT NULL,
      entity_type text,
      entity_id integer,
      details jsonb,
      created_at timestamptz NOT NULL DEFAULT now()
    )`);
    await qr.query('CREATE INDEX idx_audit_created ON audit_log(created_at)');
    await qr.query('CREATE INDEX idx_audit_actor ON audit_log(actor_id)');

    await qr.query(`CREATE TABLE categories (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name text NOT NULL UNIQUE,
      color text NOT NULL DEFAULT '#2563eb',
      created_at timestamptz NOT NULL DEFAULT now()
    )`);

    await qr.query(`CREATE TABLE branches (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name text NOT NULL,
      code varchar UNIQUE,
      address text NOT NULL DEFAULT '',
      phone text NOT NULL DEFAULT '',
      status text NOT NULL DEFAULT 'active' CONSTRAINT branches_status_chk CHECK (status IN ('active','disabled')),
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz
    )`);

    await qr.query(`CREATE TABLE user_branches (
      user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      branch_id integer NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
      is_primary integer NOT NULL DEFAULT 0 CONSTRAINT ub_primary_chk CHECK (is_primary IN (0,1)),
      created_at timestamptz NOT NULL DEFAULT now(),
      PRIMARY KEY (user_id, branch_id)
    )`);
    await qr.query('CREATE INDEX idx_user_branches_branch ON user_branches(branch_id)');

    await qr.query(`CREATE TABLE products (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name text NOT NULL,
      barcode text UNIQUE,
      price double precision NOT NULL CONSTRAINT products_price_chk CHECK (price >= 0),
      cost double precision NOT NULL DEFAULT 0 CONSTRAINT products_cost_chk CHECK (cost >= 0),
      quantity integer NOT NULL DEFAULT 0 CONSTRAINT products_qty_chk CHECK (quantity >= 0),
      low_stock_threshold integer NOT NULL DEFAULT 5 CONSTRAINT products_lst_chk CHECK (low_stock_threshold >= 0),
      category text DEFAULT '',
      category_id integer REFERENCES categories(id),
      reorder_qty integer NOT NULL DEFAULT 0 CONSTRAINT products_reorder_chk CHECK (reorder_qty >= 0),
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz
    )`);
    await qr.query('CREATE INDEX idx_products_barcode ON products(barcode)');
    await qr.query('CREATE INDEX idx_products_quantity ON products(quantity)');

    await qr.query(`CREATE TABLE suppliers (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name text NOT NULL,
      phone text NOT NULL DEFAULT '',
      email text NOT NULL DEFAULT '',
      address text NOT NULL DEFAULT '',
      notes text NOT NULL DEFAULT '',
      status text NOT NULL DEFAULT 'active' CONSTRAINT suppliers_status_chk CHECK (status IN ('active','disabled')),
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz
    )`);
    await qr.query("CREATE INDEX idx_suppliers_name ON suppliers (name)");
    await qr.query('CREATE INDEX idx_suppliers_status ON suppliers(status)');

    await qr.query(`CREATE TABLE sales (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      invoice_no varchar NOT NULL UNIQUE,
      subtotal double precision NOT NULL,
      tax_total double precision NOT NULL DEFAULT 0,
      discount double precision NOT NULL DEFAULT 0,
      total double precision NOT NULL,
      paid double precision NOT NULL,
      change_amount double precision NOT NULL DEFAULT 0,
      payment_method text NOT NULL DEFAULT 'cash',
      branch_id integer REFERENCES branches(id),
      created_at timestamptz NOT NULL DEFAULT now()
    )`);

    await qr.query(`CREATE TABLE sale_items (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      sale_id integer NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
      product_id integer NOT NULL REFERENCES products(id),
      product_name text NOT NULL,
      quantity integer NOT NULL CONSTRAINT sale_items_qty_chk CHECK (quantity > 0),
      unit_price double precision NOT NULL,
      unit_cost double precision NOT NULL DEFAULT 0,
      tax_rate double precision NOT NULL DEFAULT 0,
      line_subtotal double precision NOT NULL,
      line_tax double precision NOT NULL,
      line_total double precision NOT NULL
    )`);
    await qr.query('CREATE INDEX idx_sales_created ON sales(created_at)');
    await qr.query('CREATE INDEX idx_sale_items_sale ON sale_items(sale_id)');
    await qr.query('CREATE INDEX idx_sales_branch ON sales(branch_id)');

    await qr.query(`CREATE TABLE inventory_movements (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,
      change integer NOT NULL,
      reason text NOT NULL,
      note text,
      ref_type text,
      ref_id integer,
      balance_after integer NOT NULL,
      actor_id integer REFERENCES users(id) ON DELETE SET NULL,
      balance_before integer,
      reason_code text,
      branch_id integer REFERENCES branches(id),
      created_at timestamptz NOT NULL DEFAULT now()
    )`);
    await qr.query('CREATE INDEX idx_movements_product ON inventory_movements(product_id)');
    await qr.query('CREATE INDEX idx_movements_ref ON inventory_movements(ref_type, ref_id)');
    await qr.query('CREATE INDEX idx_movements_actor ON inventory_movements(actor_id)');
    await qr.query('CREATE INDEX idx_movements_created ON inventory_movements(created_at)');
    await qr.query('CREATE INDEX idx_movements_branch ON inventory_movements(branch_id)');

    await qr.query(`CREATE TABLE settings (
      key text PRIMARY KEY,
      value text NOT NULL
    )`);

    // ---- M002 suppliers done above; M003 purchasing ----
    await qr.query(`CREATE TABLE purchase_orders (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      ref varchar UNIQUE,
      supplier_id integer NOT NULL REFERENCES suppliers(id),
      status text NOT NULL DEFAULT 'draft' CONSTRAINT po_status_chk CHECK (status IN ('draft','submitted','approved','partially_received','fully_received','cancelled')),
      expected_at text,
      notes text NOT NULL DEFAULT '',
      branch_id integer REFERENCES branches(id),
      created_by integer REFERENCES users(id) ON DELETE SET NULL,
      approved_by integer REFERENCES users(id) ON DELETE SET NULL,
      approved_at timestamptz,
      cancelled_by integer REFERENCES users(id) ON DELETE SET NULL,
      cancelled_at timestamptz,
      cancel_reason text NOT NULL DEFAULT '',
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz
    )`);

    await qr.query(`CREATE TABLE purchase_order_items (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      po_id integer NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
      product_id integer NOT NULL REFERENCES products(id),
      qty integer NOT NULL CONSTRAINT poi_qty_chk CHECK (qty > 0),
      received_qty integer NOT NULL DEFAULT 0 CONSTRAINT poi_recv_chk CHECK (received_qty >= 0),
      unit_cost double precision NOT NULL CONSTRAINT poi_cost_chk CHECK (unit_cost >= 0),
      created_at timestamptz NOT NULL DEFAULT now()
    )`);

    await qr.query(`CREATE TABLE grns (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      ref varchar UNIQUE,
      po_id integer NOT NULL REFERENCES purchase_orders(id),
      supplier_id integer REFERENCES suppliers(id) ON DELETE SET NULL,
      branch_id integer REFERENCES branches(id),
      received_at timestamptz NOT NULL,
      notes text NOT NULL DEFAULT '',
      received_by integer REFERENCES users(id) ON DELETE SET NULL,
      created_at timestamptz NOT NULL DEFAULT now()
    )`);

    await qr.query(`CREATE TABLE grn_items (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      grn_id integer NOT NULL REFERENCES grns(id) ON DELETE CASCADE,
      po_item_id integer NOT NULL REFERENCES purchase_order_items(id),
      product_id integer NOT NULL REFERENCES products(id),
      qty_received integer NOT NULL CONSTRAINT grni_qty_chk CHECK (qty_received > 0),
      qty_damaged integer NOT NULL DEFAULT 0 CONSTRAINT grni_dmg_chk CHECK (qty_damaged >= 0),
      unit_cost double precision NOT NULL CONSTRAINT grni_cost_chk CHECK (unit_cost >= 0)
    )`);

    await qr.query('CREATE INDEX idx_po_supplier ON purchase_orders(supplier_id)');
    await qr.query('CREATE INDEX idx_po_status ON purchase_orders(status)');
    await qr.query('CREATE INDEX idx_po_items_po ON purchase_order_items(po_id)');
    await qr.query('CREATE INDEX idx_po_items_product ON purchase_order_items(product_id)');
    await qr.query('CREATE INDEX idx_grns_po ON grns(po_id)');
    await qr.query('CREATE INDEX idx_grns_supplier ON grns(supplier_id)');
    await qr.query('CREATE INDEX idx_grn_items_grn ON grn_items(grn_id)');
    await qr.query('CREATE INDEX idx_grn_items_product ON grn_items(product_id)');
    await qr.query('CREATE INDEX idx_po_branch ON purchase_orders(branch_id)');
    await qr.query('CREATE INDEX idx_grns_branch ON grns(branch_id)');

    // ---- M004 advanced inventory ----
    await qr.query(`CREATE TABLE stock_reconciliations (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,
      system_qty integer NOT NULL CONSTRAINT recon_sys_chk CHECK (system_qty >= 0),
      counted_qty integer NOT NULL CONSTRAINT recon_cnt_chk CHECK (counted_qty >= 0),
      diff_qty integer NOT NULL,
      status text NOT NULL DEFAULT 'open' CONSTRAINT recon_status_chk CHECK (status IN ('open','applied','cancelled','stale')),
      reason_code text NOT NULL,
      note text NOT NULL DEFAULT '',
      branch_id integer REFERENCES branches(id),
      created_by integer REFERENCES users(id) ON DELETE SET NULL,
      applied_by integer REFERENCES users(id) ON DELETE SET NULL,
      applied_at timestamptz,
      movement_id integer REFERENCES inventory_movements(id),
      created_at timestamptz NOT NULL DEFAULT now()
    )`);
    await qr.query('CREATE INDEX idx_recon_product ON stock_reconciliations(product_id)');
    await qr.query('CREATE INDEX idx_recon_status ON stock_reconciliations(status)');
    await qr.query('CREATE INDEX idx_recon_branch ON stock_reconciliations(branch_id)');

    await qr.query(`CREATE TABLE cost_history (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,
      source_type text NOT NULL CONSTRAINT ch_source_chk CHECK (source_type IN ('initial','grn','manual')),
      grn_id integer REFERENCES grns(id) ON DELETE SET NULL,
      supplier_id integer REFERENCES suppliers(id) ON DELETE SET NULL,
      branch_id integer REFERENCES branches(id),
      qty_received integer CONSTRAINT ch_qty_chk CHECK (qty_received IS NULL OR qty_received >= 0),
      unit_cost double precision NOT NULL CONSTRAINT ch_cost_chk CHECK (unit_cost >= 0),
      prev_cost double precision,
      new_cost double precision,
      actor_id integer REFERENCES users(id) ON DELETE SET NULL,
      created_at timestamptz NOT NULL DEFAULT now()
    )`);
    await qr.query('CREATE INDEX idx_cost_history_product ON cost_history(product_id)');
    await qr.query('CREATE INDEX idx_cost_branch ON cost_history(branch_id)');

    // ---- M005 multi-branch: branch_inventory + stock_transfers ----
    // (branches / user_branches are created earlier for FK ordering)
    await qr.query(`CREATE TABLE branch_inventory (
      branch_id integer NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
      product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,
      quantity integer NOT NULL DEFAULT 0 CONSTRAINT bi_qty_chk CHECK (quantity >= 0),
      cost double precision NOT NULL DEFAULT 0 CONSTRAINT bi_cost_chk CHECK (cost >= 0),
      low_stock_threshold integer NOT NULL DEFAULT 5 CONSTRAINT bi_lst_chk CHECK (low_stock_threshold >= 0),
      reorder_qty integer NOT NULL DEFAULT 0 CONSTRAINT bi_reorder_chk CHECK (reorder_qty >= 0),
      updated_at timestamptz,
      PRIMARY KEY (branch_id, product_id)
    )`);
    await qr.query('CREATE INDEX idx_branch_inventory_product ON branch_inventory(product_id)');

    await qr.query(`CREATE TABLE stock_transfers (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      ref varchar UNIQUE,
      source_branch_id integer NOT NULL REFERENCES branches(id),
      dest_branch_id integer NOT NULL REFERENCES branches(id),
      status text NOT NULL DEFAULT 'draft' CONSTRAINT st_status_chk CHECK (status IN ('draft','submitted','approved','dispatched','partially_received','received','cancelled')),
      notes text NOT NULL DEFAULT '',
      created_by integer REFERENCES users(id) ON DELETE SET NULL,
      approved_by integer REFERENCES users(id) ON DELETE SET NULL,
      approved_at timestamptz,
      last_dispatched_by integer REFERENCES users(id) ON DELETE SET NULL,
      last_dispatched_at timestamptz,
      last_received_by integer REFERENCES users(id) ON DELETE SET NULL,
      last_received_at timestamptz,
      cancelled_by integer REFERENCES users(id) ON DELETE SET NULL,
      cancelled_at timestamptz,
      cancel_reason text NOT NULL DEFAULT '',
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz
    )`);

    await qr.query(`CREATE TABLE stock_transfer_items (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      transfer_id integer NOT NULL REFERENCES stock_transfers(id) ON DELETE CASCADE,
      product_id integer NOT NULL REFERENCES products(id),
      qty integer NOT NULL CONSTRAINT sti_qty_chk CHECK (qty > 0),
      dispatched_qty integer NOT NULL DEFAULT 0 CONSTRAINT sti_disp_chk CHECK (dispatched_qty >= 0),
      received_qty integer NOT NULL DEFAULT 0 CONSTRAINT sti_recv_chk CHECK (received_qty >= 0),
      unit_cost double precision CONSTRAINT sti_cost_chk CHECK (unit_cost IS NULL OR unit_cost >= 0)
    )`);

    await qr.query('CREATE INDEX idx_transfers_source ON stock_transfers(source_branch_id)');
    await qr.query('CREATE INDEX idx_transfers_dest ON stock_transfers(dest_branch_id)');
    await qr.query('CREATE INDEX idx_transfers_status ON stock_transfers(status)');
    await qr.query('CREATE INDEX idx_transfer_items_transfer ON stock_transfer_items(transfer_id)');
    await qr.query('CREATE INDEX idx_transfer_items_product ON stock_transfer_items(product_id)');

    // ---- Seeds (parity with Electron seed) ----
    await qr.query(
      "INSERT INTO branches (name, code, status) VALUES ('الفرع الرئيسي', 'MAIN', 'active')",
    );
    const defaults: [string, string][] = [
      ['store_name', 'متجري'],
      ['tax_rate', '15'],
      ['currency', 'ر.س'],
      ['invoice_seq', '0'],
      ['lang', 'ar'],
      ['theme', 'light'],
    ];
    for (const [k, v] of defaults) {
      await qr.query('INSERT INTO settings (key, value) VALUES ($1, $2) ON CONFLICT (key) DO NOTHING', [k, v]);
    }
  }

  async down(qr: QueryRunner): Promise<void> {
    const tables = [
      'stock_transfer_items', 'stock_transfers', 'branch_inventory', 'user_branches', 'branches',
      'cost_history', 'stock_reconciliations', 'grn_items', 'grns', 'purchase_order_items',
      'purchase_orders', 'sale_items', 'sales', 'inventory_movements', 'products', 'categories',
      'suppliers', 'settings', 'audit_log', 'refresh_tokens', 'users',
    ];
    for (const t of tables) {
      await qr.query(`DROP TABLE IF EXISTS ${t} CASCADE`);
    }
  }
}
