import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Phase 29: SaaS multi-tenancy.
 *
 * Architecture:
 *  - Platform accounts (users) connect to organizations via organization_members.
 *  - Tenant context is derived server-side from authenticated membership.
 *  - "Global" entities (products, categories, suppliers) carry organization_id.
 *  - Branch-scoped records (sales, POs, GRNs, transfers, inventory, etc.) are
 *    transitively scoped through branches.organization_id.
 *  - Unique constraints are scoped per-org (barcode, ref numbers, names).
 *  - Sequences live in org_settings so each org's invoice/PO numbering is independent.
 *  - All existing data is migrated into org #1 (default organization).
 */
export class MultiTenancy2900000000000 implements MigrationInterface {
  public async up(qr: QueryRunner): Promise<void> {
    // ============================================================
    // 1. Platform-level tables: organizations + membership
    // ============================================================
    await qr.query(`
      CREATE TABLE organizations (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        slug text NOT NULL UNIQUE,
        status text NOT NULL DEFAULT 'active'
          CONSTRAINT org_status_chk CHECK (status IN ('active','disabled','suspended')),
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz
      )
    `);

    // ============================================================
    // 2. Seed default org BEFORE adding FK columns (Postgres enforces
    //    FK on existing rows at ADD COLUMN time).
    // ============================================================
    await qr.query(
      `INSERT INTO organizations (id, name, slug, status) VALUES (1, 'المتجر الافتراضي', 'default', 'active')`,
    );
    await qr.query(`SELECT setval('organizations_id_seq', GREATEST((SELECT MAX(id) FROM organizations), 1))`);

    // ============================================================
    // 3. Membership table + org_settings
    // ============================================================
    await qr.query(`
      CREATE TABLE organization_members (
        user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        organization_id integer NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        role text NOT NULL DEFAULT 'member'
          CONSTRAINT om_role_chk CHECK (role IN ('owner','admin','member')),
        status text NOT NULL DEFAULT 'active'
          CONSTRAINT om_status_chk CHECK (status IN ('active','disabled')),
        created_at timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY (user_id, organization_id)
      )
    `);
    await qr.query(`CREATE INDEX idx_om_org ON organization_members(organization_id)`);

    await qr.query(`
      CREATE TABLE org_settings (
        organization_id integer NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        key text NOT NULL,
        value text NOT NULL DEFAULT '',
        PRIMARY KEY (organization_id, key)
      )
    `);

    // ============================================================
    // 4. Add organization_id to all tables.
    //    Org #1 now exists, so FK constraints are satisfied by DEFAULT 1.
    // ============================================================
    await qr.query(`ALTER TABLE branches ADD COLUMN organization_id integer NOT NULL DEFAULT 1 REFERENCES organizations(id)`);
    await qr.query(`ALTER TABLE products ADD COLUMN organization_id integer NOT NULL DEFAULT 1 REFERENCES organizations(id)`);
    await qr.query(`ALTER TABLE categories ADD COLUMN organization_id integer NOT NULL DEFAULT 1 REFERENCES organizations(id)`);
    await qr.query(`ALTER TABLE suppliers ADD COLUMN organization_id integer NOT NULL DEFAULT 1 REFERENCES organizations(id)`);
    await qr.query(`ALTER TABLE audit_log ADD COLUMN organization_id integer REFERENCES organizations(id)`);
    await qr.query(`ALTER TABLE sync_operations ADD COLUMN organization_id integer REFERENCES organizations(id)`);
    await qr.query(`ALTER TABLE sync_conflicts ADD COLUMN organization_id integer REFERENCES organizations(id)`);
    await qr.query(`ALTER TABLE sales ADD COLUMN organization_id integer NOT NULL DEFAULT 1 REFERENCES organizations(id)`);
    await qr.query(`ALTER TABLE purchase_orders ADD COLUMN organization_id integer NOT NULL DEFAULT 1 REFERENCES organizations(id)`);
    await qr.query(`ALTER TABLE grns ADD COLUMN organization_id integer NOT NULL DEFAULT 1 REFERENCES organizations(id)`);
    await qr.query(`ALTER TABLE stock_transfers ADD COLUMN organization_id integer NOT NULL DEFAULT 1 REFERENCES organizations(id)`);

    // ============================================================
    // 5. Indexes on the new tenant columns.
    // ============================================================
    await qr.query(`CREATE INDEX idx_branches_org ON branches(organization_id)`);
    await qr.query(`CREATE INDEX idx_products_org ON products(organization_id)`);
    await qr.query(`CREATE INDEX idx_categories_org ON categories(organization_id)`);
    await qr.query(`CREATE INDEX idx_suppliers_org ON suppliers(organization_id)`);
    await qr.query(`CREATE INDEX idx_audit_org ON audit_log(organization_id)`);
    await qr.query(`CREATE INDEX idx_sync_ops_org ON sync_operations(organization_id)`);
    await qr.query(`CREATE INDEX idx_conflicts_org ON sync_conflicts(organization_id)`);

    // ============================================================
    // 6. Drop global unique constraints -> replace with per-org.
    // ============================================================
    await qr.query(`ALTER TABLE products DROP CONSTRAINT IF EXISTS products_barcode_key`);
    await qr.query(
      `CREATE UNIQUE INDEX idx_products_barcode_per_org ON products(organization_id, barcode) WHERE barcode IS NOT NULL`,
    );

    await qr.query(`ALTER TABLE categories DROP CONSTRAINT IF EXISTS categories_name_key`);
    await qr.query(
      `CREATE UNIQUE INDEX idx_categories_name_per_org ON categories(organization_id, name)`,
    );

    await qr.query(`ALTER TABLE branches DROP CONSTRAINT IF EXISTS branches_code_key`);
    await qr.query(
      `CREATE UNIQUE INDEX idx_branches_code_per_org ON branches(organization_id, code) WHERE code IS NOT NULL`,
    );

    await qr.query(`ALTER TABLE sales DROP CONSTRAINT IF EXISTS sales_invoice_no_key`);
    await qr.query(
      `CREATE UNIQUE INDEX idx_sales_invoice_per_org ON sales(organization_id, invoice_no)`,
    );

    await qr.query(`ALTER TABLE purchase_orders DROP CONSTRAINT IF EXISTS purchase_orders_ref_key`);
    await qr.query(
      `CREATE UNIQUE INDEX idx_po_ref_per_org ON purchase_orders(organization_id, ref) WHERE ref IS NOT NULL`,
    );

    await qr.query(`ALTER TABLE grns DROP CONSTRAINT IF EXISTS grns_ref_key`);
    await qr.query(
      `CREATE UNIQUE INDEX idx_grns_ref_per_org ON grns(organization_id, ref) WHERE ref IS NOT NULL`,
    );

    await qr.query(`ALTER TABLE stock_transfers DROP CONSTRAINT IF EXISTS stock_transfers_ref_key`);
    await qr.query(
      `CREATE UNIQUE INDEX idx_transfers_ref_per_org ON stock_transfers(organization_id, ref) WHERE ref IS NOT NULL`,
    );

    // ============================================================
    // 7. Seed default org_settings from global settings.
    // ============================================================
    await qr.query(`
      INSERT INTO org_settings (organization_id, key, value)
      SELECT 1, key, value FROM settings
      WHERE key IN ('store_name','tax_rate','currency','invoice_seq','po_seq','grn_seq','transfer_seq','lang','theme')
      ON CONFLICT (organization_id, key) DO NOTHING
    `);

    // ============================================================
    // 8. Backfill audit_log organization_id for existing records.
    // ============================================================
    await qr.query(
      `UPDATE audit_log SET organization_id = COALESCE(
        (SELECT om.organization_id FROM organization_members om WHERE om.user_id = audit_log.actor_id AND om.status='active' LIMIT 1),
        1) WHERE organization_id IS NULL`,
    );

    // ============================================================
    // 9. Composite org-scoped indexes for transitive records.
    // ============================================================
    await qr.query(`CREATE INDEX idx_sales_org ON sales(organization_id)`);
    await qr.query(`CREATE INDEX idx_po_org ON purchase_orders(organization_id)`);
    await qr.query(`CREATE INDEX idx_grns_org ON grns(organization_id)`);
    await qr.query(`CREATE INDEX idx_transfers_org ON stock_transfers(organization_id)`);
  }

  public async down(qr: QueryRunner): Promise<void> {
    await qr.query(`DROP TABLE IF EXISTS org_settings`);
    await qr.query(`DROP TABLE IF EXISTS organization_members`);
    await qr.query(`DROP TABLE IF EXISTS organizations`);

    for (const tbl of ['products', 'categories', 'suppliers', 'branches',
                       'audit_log', 'sync_operations', 'sync_conflicts',
                       'sales', 'purchase_orders', 'grns', 'stock_transfers']) {
      await qr.query(`ALTER TABLE ${tbl} DROP COLUMN IF EXISTS organization_id`);
    }
  }
}
