import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Phase 30: Subscription & Billing.
 *
 * Tables:
 *  - subscription_plans: available plans (trial, basic, pro, enterprise)
 *  - organization_subscriptions: active subscription per org
 *  - billing_events: audit trail for all billing events
 *  - billing_invoices: invoice/billing history
 *
 * All existing orgs get a default trial subscription (safe, no data loss).
 */
export class SubscriptionBilling3000000000000 implements MigrationInterface {
  public async up(qr: QueryRunner): Promise<void> {
    // ============================================================
    // 1. Subscription plans
    // ============================================================
    await qr.query(`
      CREATE TABLE subscription_plans (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        slug text NOT NULL UNIQUE,
        description text NOT NULL DEFAULT '',
        price_monthly double precision NOT NULL DEFAULT 0,
        price_yearly double precision NOT NULL DEFAULT 0,
        currency text NOT NULL DEFAULT 'USD',
        trial_days integer NOT NULL DEFAULT 0,
        max_users integer NOT NULL DEFAULT 0,
        max_branches integer NOT NULL DEFAULT 0,
        max_products integer NOT NULL DEFAULT 0,
        features jsonb NOT NULL DEFAULT '{}'::jsonb,
        is_active boolean NOT NULL DEFAULT true,
        sort_order integer NOT NULL DEFAULT 0,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz
      )
    `);

    // ============================================================
    // 2. Organization subscriptions (one per org)
    // ============================================================
    await qr.query(`
      CREATE TABLE organization_subscriptions (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL UNIQUE REFERENCES organizations(id) ON DELETE CASCADE,
        plan_id integer NOT NULL REFERENCES subscription_plans(id),
        status text NOT NULL DEFAULT 'trialing'
          CONSTRAINT os_status_chk CHECK (status IN ('trialing','active','past_due','cancelled','suspended')),
        trial_starts_at timestamptz,
        trial_ends_at timestamptz,
        current_period_starts_at timestamptz,
        current_period_ends_at timestamptz,
        cancelled_at timestamptz,
        cancel_reason text NOT NULL DEFAULT '',
        external_subscription_id text,
        metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz
      )
    `);
    await qr.query(`CREATE INDEX idx_os_org ON organization_subscriptions(organization_id)`);
    await qr.query(`CREATE INDEX idx_os_status ON organization_subscriptions(status)`);

    // ============================================================
    // 3. Billing events (audit trail)
    // ============================================================
    await qr.query(`
      CREATE TABLE billing_events (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer REFERENCES organizations(id) ON DELETE SET NULL,
        subscription_id integer REFERENCES organization_subscriptions(id) ON DELETE SET NULL,
        event_type text NOT NULL,
        provider text NOT NULL DEFAULT 'manual',
        provider_event_id text,
        payload jsonb NOT NULL DEFAULT '{}'::jsonb,
        status text NOT NULL DEFAULT 'pending'
          CONSTRAINT be_status_chk CHECK (status IN ('pending','processed','failed')),
        error_message text NOT NULL DEFAULT '',
        idempotency_key text NOT NULL UNIQUE,
        created_at timestamptz NOT NULL DEFAULT now()
      )
    `);
    await qr.query(`CREATE INDEX idx_be_org ON billing_events(organization_id)`);
    await qr.query(`CREATE INDEX idx_be_created ON billing_events(created_at)`);

    // ============================================================
    // 4. Billing invoices
    // ============================================================
    await qr.query(`
      CREATE TABLE billing_invoices (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        subscription_id integer REFERENCES organization_subscriptions(id) ON DELETE SET NULL,
        invoice_number text NOT NULL,
        amount double precision NOT NULL DEFAULT 0,
        currency text NOT NULL DEFAULT 'USD',
        status text NOT NULL DEFAULT 'draft'
          CONSTRAINT bi_status_chk CHECK (status IN ('draft','open','paid','void','uncollectible')),
        period_starts_at timestamptz,
        period_ends_at timestamptz,
        paid_at timestamptz,
        external_invoice_id text,
        metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
        created_at timestamptz NOT NULL DEFAULT now()
      )
    `);
    await qr.query(`CREATE INDEX idx_bi_org ON billing_invoices(organization_id)`);

    // ============================================================
    // 5. Add subscription_id FK to organizations
    // ============================================================
    await qr.query(`ALTER TABLE organizations ADD COLUMN subscription_id integer REFERENCES organization_subscriptions(id)`);
    await qr.query(`CREATE INDEX idx_orgs_sub ON organizations(subscription_id)`);

    // ============================================================
    // 6. Seed default subscription plans
    // ============================================================
    await qr.query(`
      INSERT INTO subscription_plans (name, slug, description, price_monthly, price_yearly, currency, trial_days, max_users, max_branches, max_products, features, is_active, sort_order)
      VALUES
        ('Free Trial', 'trial', '1-day free trial with full access', 0, 0, 'USD', 1, 5, 2, 100,
         '{"products":true,"inventory":true,"sales":true,"purchases":true,"transfers":true,"reports":true,"pos":true}',
         true, 0),
        ('Basic', 'basic', 'For small businesses', 29.99, 299.99, 'USD', 0, 5, 3, 500,
         '{"products":true,"inventory":true,"sales":true,"purchases":false,"transfers":false,"reports":true,"pos":true}',
         true, 1),
        ('Pro', 'pro', 'For growing businesses', 79.99, 799.99, 'USD', 0, 20, 10, 5000,
         '{"products":true,"inventory":true,"sales":true,"purchases":true,"transfers":true,"reports":true,"pos":true}',
         true, 2),
        ('Enterprise', 'enterprise', 'For large organizations', 199.99, 1999.99, 'USD', 0, 0, 0, 0,
         '{"products":true,"inventory":true,"sales":true,"purchases":true,"transfers":true,"reports":true,"pos":true}',
         true, 3)
    `);

    // ============================================================
    // 7. Create default trial subscription for all existing orgs
    // ============================================================
    const trialPlan = await qr.query(`SELECT id FROM subscription_plans WHERE slug='trial'`);
    if (trialPlan[0]) {
      const planId = trialPlan[0].id;
      const now = new Date();
      const trialEnd = new Date(now.getTime() + 1 * 24 * 60 * 60 * 1000);
      // Create subscriptions for all orgs without one
      await qr.query(`
        INSERT INTO organization_subscriptions (organization_id, plan_id, status, trial_starts_at, trial_ends_at, current_period_starts_at, current_period_ends_at)
        SELECT o.id, $1, 'trialing', now(), $2, now(), $2
        FROM organizations o
        WHERE o.id NOT IN (SELECT organization_id FROM organization_subscriptions)
      `, [planId, trialEnd.toISOString()]);
      // Link orgs to their subscriptions
      await qr.query(`
        UPDATE organizations o
        SET subscription_id = os.id
        FROM organization_subscriptions os
        WHERE os.organization_id = o.id AND o.subscription_id IS NULL
      `);
    }

    // ============================================================
    // 8. Log initial trial creation events
    // ============================================================
    await qr.query(`
      INSERT INTO billing_events (organization_id, subscription_id, event_type, provider, payload, status, idempotency_key)
      SELECT os.organization_id, os.id, 'subscription.trial_started', 'system',
             jsonb_build_object('plan_id', os.plan_id, 'trial_ends_at', os.trial_ends_at),
             'processed', 'trial-' || os.organization_id || '-' || os.id
      FROM organization_subscriptions os
      WHERE os.status = 'trialing'
    `);
  }

  public async down(qr: QueryRunner): Promise<void> {
    await qr.query(`ALTER TABLE organizations DROP COLUMN IF EXISTS subscription_id`);
    await qr.query(`DROP TABLE IF EXISTS billing_invoices`);
    await qr.query(`DROP TABLE IF EXISTS billing_events`);
    await qr.query(`DROP TABLE IF EXISTS organization_subscriptions`);
    await qr.query(`DROP TABLE IF EXISTS subscription_plans`);
  }
}
