import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Phase 32: AI Insights — stores deterministic AI analysis results.
 *
 * Table:
 *  - ai_insights: demand forecasts, anomaly alerts, reorder recommendations, summaries
 *
 * All insights are advisory — never auto-execute financial/destructive actions.
 * Insights are scoped to organization_id for full tenant isolation.
 */
export class AiInsights3200000000000 implements MigrationInterface {
  public async up(qr: QueryRunner): Promise<void> {
    await qr.query(`
      CREATE TABLE ai_insights (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        branch_id integer REFERENCES branches(id) ON DELETE SET NULL,
        insight_type text NOT NULL
          CONSTRAINT ai_type_chk CHECK (insight_type IN (
            'demand_forecast', 'anomaly', 'reorder_recommendation',
            'slow_moving', 'business_summary', 'cost_trend', 'profit_alert'
          )),
        entity_type text,
        entity_id integer,
        severity text NOT NULL DEFAULT 'info'
          CONSTRAINT ai_severity_chk CHECK (severity IN ('info', 'warning', 'critical', 'positive')),
        title text NOT NULL,
        message text NOT NULL DEFAULT '',
        data jsonb NOT NULL DEFAULT '{}'::jsonb,
        status text NOT NULL DEFAULT 'active'
          CONSTRAINT ai_status_chk CHECK (status IN ('active', 'dismissed', 'acted_upon')),
        dismissed_at timestamptz,
        created_at timestamptz NOT NULL DEFAULT now()
      )
    `);

    await qr.query(`CREATE INDEX idx_ai_insights_org ON ai_insights(organization_id)`);
    await qr.query(`CREATE INDEX idx_ai_insights_org_type ON ai_insights(organization_id, insight_type)`);
    await qr.query(`CREATE INDEX idx_ai_insights_org_status ON ai_insights(organization_id, status)`);
    await qr.query(`CREATE INDEX idx_ai_insights_branch ON ai_insights(branch_id) WHERE branch_id IS NOT NULL`);
  }

  public async down(qr: QueryRunner): Promise<void> {
    await qr.query(`DROP TABLE IF EXISTS ai_insights`);
  }
}
