import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Phase 33: Owner Control Center & License Management.
 *
 * Extends:
 *  - organization_subscriptions: add license_code, user_limit, branch_limit,
 *    features (jsonb), notes, created_by, extended_at
 *
 * Creates:
 *  - license_history: immutable audit trail of all license state changes
 *
 * Zero data loss. Additive columns only.
 */
export class OwnerLicense3300000000000 implements MigrationInterface {
  public async up(qr: QueryRunner): Promise<void> {
    // ── 1. Extend organization_subscriptions with license fields ──
    const cols = [
      `ADD COLUMN IF NOT EXISTS license_code varchar(32)`,
      `ADD COLUMN IF NOT EXISTS user_limit integer NOT NULL DEFAULT 0`,
      `ADD COLUMN IF NOT EXISTS branch_limit integer NOT NULL DEFAULT 0`,
      `ADD COLUMN IF NOT EXISTS features jsonb NOT NULL DEFAULT '{}'::jsonb`,
      `ADD COLUMN IF NOT EXISTS notes text NOT NULL DEFAULT ''`,
      `ADD COLUMN IF NOT EXISTS created_by integer`,
      `ADD COLUMN IF NOT EXISTS extended_at timestamptz`,
    ];
    for (const col of cols) {
      await qr.query(`ALTER TABLE organization_subscriptions ${col}`);
    }

    // Unique index on license_code (nullable-safe: only index non-null values)
    await qr.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS idx_os_license_code
      ON organization_subscriptions(license_code)
      WHERE license_code IS NOT NULL
    `);

    // Expand status CHECK to include 'expired', 'revoked', 'pending' for license lifecycle
    await qr.query(`
      ALTER TABLE organization_subscriptions DROP CONSTRAINT IF EXISTS os_status_chk
    `);
    await qr.query(`
      ALTER TABLE organization_subscriptions ADD CONSTRAINT os_status_chk
      CHECK (status IN ('trialing','active','past_due','cancelled','suspended','expired','revoked','pending'))
    `);

    // ── 2. License history ──
    await qr.query(`
      CREATE TABLE IF NOT EXISTS license_history (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        subscription_id integer REFERENCES organization_subscriptions(id) ON DELETE SET NULL,
        action text NOT NULL
          CONSTRAINT lh_action_chk CHECK (action IN (
            'created','activated','extended','suspended','reactivated',
            'revoked','plan_changed','limits_changed','notes_changed'
          )),
        actor_id integer,
        license_code text,
        previous_value jsonb,
        new_value jsonb,
        reason text NOT NULL DEFAULT '',
        created_at timestamptz NOT NULL DEFAULT now()
      )
    `);

    await qr.query(`CREATE INDEX IF NOT EXISTS idx_lh_org ON license_history(organization_id)`);
    await qr.query(`CREATE INDEX IF NOT EXISTS idx_lh_org_action ON license_history(organization_id, action)`);
    await qr.query(`CREATE INDEX IF NOT EXISTS idx_lh_sub ON license_history(subscription_id) WHERE subscription_id IS NOT NULL`);
  }

  public async down(qr: QueryRunner): Promise<void> {
    // Restore original status CHECK constraint
    await qr.query(`ALTER TABLE organization_subscriptions DROP CONSTRAINT IF EXISTS os_status_chk`);
    await qr.query(`
      ALTER TABLE organization_subscriptions ADD CONSTRAINT os_status_chk
      CHECK (status IN ('trialing','active','past_due','cancelled','suspended'))
    `);

    await qr.query(`DROP TABLE IF EXISTS license_history`);
    await qr.query(`DROP INDEX IF EXISTS idx_os_license_code`);
    await qr.query(`ALTER TABLE organization_subscriptions DROP COLUMN IF EXISTS license_code`);
    await qr.query(`ALTER TABLE organization_subscriptions DROP COLUMN IF EXISTS user_limit`);
    await qr.query(`ALTER TABLE organization_subscriptions DROP COLUMN IF EXISTS branch_limit`);
    await qr.query(`ALTER TABLE organization_subscriptions DROP COLUMN IF EXISTS features`);
    await qr.query(`ALTER TABLE organization_subscriptions DROP COLUMN IF EXISTS notes`);
    await qr.query(`ALTER TABLE organization_subscriptions DROP COLUMN IF EXISTS created_by`);
    await qr.query(`ALTER TABLE organization_subscriptions DROP COLUMN IF EXISTS extended_at`);
  }
}
